# Generated by Django 4.2.5 on 2023-10-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nome',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
