# Generated by Django 4.2.7 on 2023-11-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_image_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='nome',
        ),
    ]
