# Generated by Django 4.2.5 on 2023-09-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papasburgueria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to=settings.AUTH_USER_MODEL),
        ),
    ]
