# Generated by Django 4.2.3 on 2023-08-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papasburgueria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Refrigerantes',
            new_name='Refrigerante',
        ),
        migrations.DeleteModel(
            name='Ingredientes',
        ),
        migrations.AlterField(
            model_name='hamburguer',
            name='ingredientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hamburguer', to='papasburgueria.ingrediente'),
        ),
    ]
