# Generated by Django 4.2.3 on 2023-08-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papasburgueria', '0002_ingrediente_rename_refrigerantes_refrigerante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigerante',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
