# Generated by Django 4.2.3 on 2023-08-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papasburgueria', '0003_alter_refrigerante_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguer',
            name='ingredientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hamburguer', to='papasburgueria.ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
