# Generated by Django 4.2.4 on 2023-08-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papasburgueria', '0003_itenscompra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refrigerante',
            new_name='Bebida',
        ),
        migrations.RenameField(
            model_name='itenscompra',
            old_name='refrigerante',
            new_name='bebida',
        ),
    ]
