# Generated by Django 4.2.5 on 2023-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papasburgueria', '0003_remove_itenscomanda_bebida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
