# Generated by Django 4.2.4 on 2023-08-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papasburgueria', '0004_alter_hamburguer_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguer',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name='hamburguer',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='hamburguer',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='hamburguer', to='papasburgueria.ingrediente'),
        ),
    ]
