# Generated by Django 5.0 on 2023-12-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papasburgueria', '0005_bebida_imagem_hamburguer_image_ingrediente_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburguer',
            old_name='image',
            new_name='imagem',
        ),
    ]
